language: node_js
node_js:
  - 'v14.15.0'
before_install:
  - npm install -g typescript
branches:
  only:
    - main
before_deploy:
  - rm -rf node_modules
  - zip -r nest-app
  - mkdir -p deploy
  - mv nest-app.zip deploy/nest-app.zip
deploy:
  - provider: s3 # AWS S3 service
    access_key_id: $AWS_ACCESS_KEY # setting in travis ci
    secret_access_key: $AWS_SECRET_KEY
    bucket: season-code-repository
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy # deploy 디렉터리에 있는 파일을 s3로 업로드 하겠다는 의미
    wait-until-deployed: true
    on:
      repo: season-lms/season-api-server
      branch: main
  - provider: codedeploy # AWS CodeDeploy Service
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: season-code-repository
    key: nest-app.zip
    bundle_type: zip # 버킷에 저장되어 있는 파일의 확장자
    application: season-api-server-code-deploy-service # AWS 배포 애플리케이션
    deployment_group: season-api-server-code-deploy-group # AWS 배포 애플리케이션에 만들어져 있는 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: season-lms/season-api-server
      branch: main
notifications:
  slack:
    secure: U/TbpBd3sFlJhjsIuQ4WCfUkfGPE/InEEGSVeH88j8O/K9SGybYtfEEsVcfRFdmbA9bLC3GbWn2L8xptPj/u8+pg7Bqt6BEATj/3uEBes80ckM4cK1y3k12Dd9ebKU4hmwM9CCdbG+ShqGqaZ2YrtCeLLGrNo8Dcf3qQVjJ7f7sTSHaKm+pc0YTlJIBSj3Ohi6mqn6eJy6D93i4kWRi/o2LkKblFztTHKm5Stn3ztkc0CYzz6HcTHH7tqVgI/f3uMwM+YNeoaBu2yChvckBYv3UjetpRI4L4EJmN0AI0tonSLNFBbVTJouwcvZb2m8bQV2i3NYK8fJ1+ZGWkazmrzj7X23Unfz3JgVAYWQ1w0DLrJK2T67KZLSjmiIZMYdPnATD0FD+3Q0TSHFoZSf9VTBzAy7MaaJgH2kHHkpNvFUP5WADe5/NX5KS9u/D4aFu18vnOuh7CniMPKgaHTJkqZa/FAh9X5cSuhvh3ARcRocFx/wFUtsFuIiVavPzJCr2KBqhq5fi9jGIofRE9ocKV7Gd3lF7IRLG9iGxPjYEsjlj5xmFALoY8sYod+Pe7R9xkc1DT6XmXKXNH0N7L8rdGURghyILRYOKwNbUYNyk+inMkGe04MgJ60O/0Pz4S//TrNucVcFibYuopXs6CCTJAb9hg6OIk6zUwCoByo26imgE=
